### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Car_Insurance_Analysis#13]
@phuntsoktseten @mchiriboga
You have made great additions to your analysis. Great work!

Here are some remaining issues for your milestone 1:

- [x] Your readme looks very similar to the version you had in the proposal. You should update the readme.
- [x] Add a link to your report on the main readme 
- [x] Add instructions to run your analysis on main readme
- [x] Add dependencies with their version information on the readme

**Suggestions:**

- You can include a flow chart/dependency diagram on your readme.

**Comment by mchiriboga** [comment]
Thanks for the feedback, Ozum. We'll implement your suggestions asap.
Just to clarify, what do you mean by the third point ("Add instructions to run your analysis on main readme")? Doesn't the `Usage` section address that?

**Comment by Nazliozum** [comment]
@mchiriboga I gave my feedback on this release of your project: https://github.com/UBC-MDS/Car_Insurance_Analysis/tree/v2.0 . This was the release completed before the deadline and it does not have that section. Now I see in your latest version that you have actually included `usage`, so you don't have to worry about that :)

**Comment by mchiriboga** [comment]
Oh, I see @Nazliozum; thanks for clarifying. I think that all of these items were addressed on the last release, [v2.0.2](https://github.com/UBC-MDS/Car_Insurance_Analysis/releases/tag/v2.0.2), so I'm closing this issue.

@phuntsoktseten 
FYI
