### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by nuranskitchen** [UBC-MDS/Car_Insurance_Analysis#21]
@mchiriboga and @phuntsoktseten great job on Milestone 2! Here are some remaining issues:

- [x] Include `make clean` argument to your instructions on make
- [x] Update the documentation at the beginning of the Makefile. As per Tiffany's instructions on this: "The Makefile must be well documented. This means comments throughout, readable code and a brief summary at the top of each file that answers who wrote it, when it was written and what it does."
- [x] Add link to `report` folder where you write "The report will be rendered into a PDF document in the report folder" on the readme
- [x] Add version info for R packages as well. Packages might have different versions even within the same R version

**Suggestions:**

- [x] Add a "Conclusion" section in your report where you discuss your results
- [ ] Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by mchiriboga** [comment]
@phuntsoktseten I submitted a [new pull request, #26] (https://github.com/UBC-MDS/Car_Insurance_Analysis/pull/26) addressing the remaining items pointed out by @Nazliozum. Can you please review it?

**Comment by mchiriboga** [comment]
@phuntsoktseten I submitted one more pull request, #27, to avoid Rplots.pdf generation. Can you please review it?
